### ISSUE TITLE
Error when 'running build_ext' ... 'No such file or directory'

### ISSUE THREAD

**Issue by ryliejamesthomas** [LogicalDash/LiSE#36]
```
running build_ext
    cythoning ELiDE/kivygarden/collider/collider.pyx to ELiDE/kivygarden/collider/collider.c
    error: [Errno 2] No such file or directory: '/tmp/pip-p2ow7jhu-build/ELiDE/kivygarden/collider/collider.pyx'
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-p2ow7jhu-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-pf3hqmuu-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-p2ow7jhu-build/
```
Any idea why this is happening?

Seems some people get this when they're not on the latest version of pip, but I'm using pip 9.0.1 (and python 3.6).

It's creating the directories fine, just this file isn't in there.

Could I need to use an earlier version?

Sorry if this is a silly question, I'm not very knowledgeable about Python.

---

Update:

Works just fine when I use git to install it instead of using the tar.gz from the Releases page. I tried re-installing python-kivy-git from the AUR and there's something up with that package, so I think that might be the problem.

I'm gunna close this.

**Comment by LogicalDash** [comment]
It's because ELiDE installs a kivy.garden package in a nonstandard way, by keeping it in a subdirectory that is also a submodule in git. It enables me to bundle kivy.garden.collider in the same wheel as ELiDE, so that you don't need to run garden yourself in order to run the thing.

I think you shouldn't have to worry about submodules just because you want to install ELiDE from source. I'll add another source package to the release with the submodules included.

It'll have to wait til I get home though.

**Comment by LogicalDash** [comment]
[Here you go.](https://github.com/LogicalDash/LiSE/releases/download/Alpha7/LiSE_alpha7_src_with_deps.tar.gz)

**Comment by ryliejamesthomas** [comment]
Thanks for that!, and the clear explanation.
